#!/usr/bin/env python3
import discord
import asyncio
import random
import time
import traceback

SPOILERS = {
' 127 Hours (2010)  ':' Aron Ralston cuts off his own arm to escape from being pined under the rock.  ',
' 300 (2006)  ':' The Spartans all die. ',
' 2001: A Space Odyssey (1968)  ':' HAL kills all the astronauts except Dave, who shuts HAL down. Then Dave travels beyond the infinite, reaches for the monolith similar to the one at the beginning of the film and becomes the next evolution of man, which explains why the apes at the beginning of the film suddenly knew how to use tools after their experience with the monolith.  ',
' Ace Ventura: Pet Detective (1994) ':' Einhorn is Finkle.  ',
' Ace Ventura: When Nature Calls (1995) ':' The tribe chase after Ace Ventura after it\'s revealed he deflowered the tribe princess.  ',
' Air Force One (1997)  ':' James Marshall kills all the terrorists and gets off the plane. ',
' Alice in Wonderland (1951)  ':' It turns out it was all a dream.  ',
' Alien (1979)  ':' Ripley is the sole survivor of the alien attack.  ',
' American Beauty (1999)  ':' Lester is killed by his gay neighbor after turning down his advances. Angela is a virgin. ',
' Antz (1998) ':' General Mandible dies, Z and Bala get married, and the ants start to rebuild the colony.  ',
' Apollo 13 (1995)  ':' The astronauts make it home.  ',
' Arsenic and Old Lace (1944) ':' Mortimer\'s aunts get commited to the mental instituion, Jonathan is arrested, and it\'s revealed that Mortimer isn\'t related to his aunts.  ',
' Avatar (2009) ':' Jake helps the Na\'vi take back Pandora and they send all the humans back to earth except for Jake, Norm and Max. Jake is then completely transfered into his avatar. ',
' Babe (1995) ':' Babe wins the sheepherding contest. ',
' Babe: Pig in the City (1998)  ':' Babe saves the farm.  ',
' Back to the Future (1985) ':' Marty makes it back to the future.  ',
' Back to the Future Part II (1989) ':' Marty burns the Almanac, but the Delorean gets struck by lightning sending Doc back to 1885.  ',
' Back to the Future Part III (1990)  ':' Marty gets back to the future, but destroys the DeLorean in the process. Then Doc, Clara and their sons show up in a time machine built from a train. ',
' Bear (2010) ':' Liz is pregnant with Nick\'s child and she\'s the only character to survive. Also, the bear used his psychic connections to the spirit world to bring these characters into this scenario so they could confront their issues head on.  ',
' A Beautiful Mind (2001) ':' Charles, William Parcher and Marcee are figment\'s of John\'s imagination.  ',
' Bee Movie (2007)  ':' The bees of world all come together and spread the pollen of the last flowers all over the planet, thus restoring the balance of nature.  ',
' The Birds (1963)  ':' Melanie is almost pecked to death by birds. Mitch, Lydia and Cathy drag her to the car and they drive into the unknown, as the birds just watch them. ',
' The Box (2009)  ':' The couple has to make a decision to kill Cameron Diez or have their son live the rest of his life blind and deaf, and they choose the former just as another couple presses the button.  ',
' A Bug\'s Life (1998)  ':' Hopper gets eaten by birds. The circus bugs go back to the circus.  ',
' Buried (2010) ':' Ryan Reynolds dies. ',
' Captain America: The First Avenger (2011) ':' Captain America is frozen in a block of ice and wakes up in modern day New York.  ',
' Cars (2006) ':' Lightning McQueen loses the race, and goes back to live in Radiator Springs.  ',
' Cars 2 (2011) ':' Axelrod was behind the whole scheme.  ',
' Chicken Run (2000)  ':' The chickens escape the chicken farm, and Ginger and Rocky end up together. ',
' Citizen Kane (1941) ':' Rosebud was his childhood sled. ',
' The Crucible (1996) ':' John Proctor, Rebecca Nurse and Martha Corey are hung.  ',
' The Crying Game (1992)  ':' Dil is a boy. ',
' The Dark Knight (2008)  ':' Batman takes the blame for the crimes Two-Face did to keep Harvey Dent\'s name pure.  ',
' Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb... (1964)  ':' The doomsday machine is activated, destorying all life on earth.  ',
' Escape from Alcatraz (1979) ':' Frank Morris and the Anglin brothers escape from Alcatraz, but whether they made it to shore or drowned is unknown. The warden assures the guards that they drowned.  ',
' The Exorcist (1973) ':' Father Merrin dies of a heart attack during the exorcism, and Father Karras slaps Regan allowed so the demon would enter his body, and when the demon does, he jumps out the window to his death in an attempt to kill the demon inside him.  ',
' Fantastic Mr. Fox (2009)  ':' The animals have to remain underground, but they have a portal to Boggis, Bunce and Bean\'s supermarket where they can steal as much food as they need. ',
' Fargo (1996)  ':' Gaear kills Jean and Carl. Marge spots him throwing the remains of Carl into wood chipper and arrests him.  ',
' Fight Club (1999) ':' Tyler Durden is an alternate personality of the nameless narrator.  ',
' Finding Nemo (2003) ':' They find Nemo. ',
' First Blood (1982)  ':' Rambo almost kills Teasle, but Trautman stops him and gets him to surrender.  ',
' Flushed Away (2006) ':' Roddy decides to stay underground and ends up with Rita.  ',
' Forrest Gump (1994) ':' Jenny dies and Forrest raises their son.  ',
' The Fugitive (1993) ':' Dr. Charles Nichols hired Frederick Sykes to kill Richard Kimble because he was getting suspicious about a miracle drug "Provasic" that did major liver damage. ',
' Gladiator (2000)  ':' Maximus is killed.  ',
' The Good Earth (1937) ':' O-lan dies just after her son\'s wedding. Wang Lung walks out onto the land and whispers, "O-lan, you are the earth." ',
' The Green Mile (1999) ':' John Coffey is executed. Later, Paul is shown to be over a hundred years old and sees Mr. Jingles is still alive. Paul watches people in his life die one at a time while wondering how much longer he\'ll be alive.  ',
' The Happening (2008)  ':' Eliot and Alma go outside to meet their doom together when suddenly the nuertoxins stop killing people. ',
' Harry Potter and the Philosopher\'s Stone (2001)  ':' Professor Quirrell is sharing a body with Lord Voldemort, but because of Lily\'s loving sacrifice, Harry is able to fend him off and Quirrell dies. ',
' Harry Potter and the Chamber of Secrets (2002)  ':' Tom Riddle is the heir of Slytherin, who is actually a memory of Lord Voldemort, and Harry manages to kill him and the Basilisk.  ',
' Harry Potter and the Prisoner of Azkaban (2004) ':' Scabbers is Peter Pettigrew who is the betrayer of the Potter\'s, but he escapes, meaning Sirius Black is still on the run from the law.  ',
' Harry Potter and the Goblet of Fire (2005)  ':' Lord Voldemort returns, by using the Tri-Wizard cup as a port key placed by Barty Crouch Jr. disguised as Mad Eye Moody and using Harry\'s blood, and kills Cedric Diggory. ',
' Harry Potter and the Order of the Phoenix (2007)  ':' Sirius Black is killed. ',
' Harry Potter and the Half-Blood Prince (2009) ':' Snape kills Dumbledore. ',
' Harry Potter and the Deathly Hallows: Part 1 (2010) ':' Bellatrix kills Dobby, and the trio are still trying to find the remaining Horcruxes. ',
' Harry Potter and the Deathly Hallows: Part 2 (2011) ':' It turns out that Harry himself is the final Horcrux and must be killed by Lord Voldemort in order for Voldemort to be defeated, so Harry sacrifices himself, but Voldemort only killed the Horcrux and Harry is able to come back from the dead to finally kill Lord Voldemort. Lupin, Tonks, Fred, Bellatrix, & Snape are all killed and Snape was a good guy all along, killing Dumbledore under his orders so Snape could be fully trusted by Lord Voldemort as Dumbledore was already dying. ',
' Harvey (1950) ':' Harvey is not imaginary and Jimmy Stewart is allowed to go home.  ',
' High Noon (1952)  ':' Kane shoots Frank Miller but throws his Marshall badge on the ground, and leaves town with his wife.  ',
' Hoodwinked! (2005)  ':' Boingo is the Goody Bandit and he\'s brought to justice.  ',
' How the Grinch Stole Christmas (2000) ':' The Grinch doesn\'t steal Christmas and his heart grows three sizes.  ',
' How to Train Your Dragon (2010) ':' The Red Death is killed, Hiccup loses his leg, and dragons are socially accepted. ',
' Inception (2010)  ':' The inception is sucessfully completed, but Cobb may or may not be in the real world and may or may not have been in limbo throughout the entire film. The film ends with the top spinning. It wobbles a bit before cutting to black. ',
' Incident in a Small Town (1994) ':' John killed his father in order to protect his mother.  ',
' The Incredibles (2004)  ':' Sydrome is sucked into a jet turbine and is chopped into bits.  ',
' Indiana Jones and the Raiders of the Lost Ark... (1981) ':' Those who look into the ark have their faces melted off. The ark is put into heavy storage where it most likely will never be found again.  ',
' Indiana Jones and the Temple of Doom (1984) ':' Indiana Jones rescues the children and brings the stone back to the village.  ',
' Indiana Jones and the Last Crusade (1989) ':' Elsa Schnider is working for Donnovan and they both die.  ',
' Indiana Jones and the Kingdom of the Crystal Skull... (2008)  ':' The skull is returned to Akator. Also Mutt is the son of Indy and Marion, and they get married. ',
' Inglourious Basterds (2009) ':' Shoshana is killed and the group succeeds in their plan to kill Hitler. ',
' Inherit the Wind (1960) ':' Cates is found guilty, but is only fined the smallest amount possible. While giving a speech immediately after the trail, Brady has a heart attack and dies.  ',
' It\'s a Wonderful Life (1946) ':' George chooses to come back to his life, realizing what a difference he\'s made, and the whole town comes together to help pay off his debt.  ',
' Jaws (1975) ':' The shark is blown up by Chief Brody. ',
' Jaws 2 (1978) ':' The shark gets electrocuted.  ',
' Jaws 3 (1983) ':' Michael Brody blows up the shark by pulling on the pin of a grenade stuck in the shark\'s teeth.  ',
' Jaws: The Revenge (1987)  ':' Ellen Brody impales the shark on the tip of the boat and the shark explodes for no reason. Also Jake survives.  ',
' Jurassic Park (1993)  ':' Genarro, Nedry, Arnold and Muldoon die. The rest get off the island.  ',
' Jurassic Park III (2001)  ':' The kid is saved, Billy is found alive and they all go home.  ',
' Kung Fu Panda (2008)  ':' Po defeats Tai Lung and becomes the Dragon Warrior. ',
' Kung Fu Panda 2 (2011)  ':' Po finds inner peace and defeats Lord Shen. He reconciles with Ping, but Po\'s real father senses him far away in a panda village.  ',
' The Lake House (2006) ':' Keeanu Reeves was the man that Sandra Bullock saw get hit by the car earlier in the film, and 2 years after the incident she goes back to the lake house to send him a letter to save his life hoping he\'ll see it, and he does. ',
' The Legend of the Titanic (1999)  ':' The octopus and the whales save all of the passengers on the Titanic. ',
' Letters from Iwo Jima (2006)  ':' The Japanese lose the battle of Iwo Jima, but Saigo survives. ',
' The Lost World: Jurassic Park (1997)  ':' The T-Rex is unleashed in San Diego but Malcolm and Harding get it back into the crate and send it back to Site B.  ',
' Madagascar (2005) ':' The animals are about to leave Madagascar, but the boat can\'t move.  ',
' Madagascar: Escape 2 Africa (2008)  ':' The animals decide to stay in Africa while the penguins and lemurs go back to New York. ',
' Meet the Robinsons (2007) ':' It turns out Lewis is Wilbur\'s father, the Bowler Hat guy is Goob and the timeline is restored.  ',
' Megamind (2010) ':' Metro Man is alive, Megamind defeats Titan and becomes a superhero. ',
' Memento (2000)  ':' Teddy dies, but Leonard lied to himself by telling himself not to believe a word Teddy says and tattooing his license plate on himself, because he was upset at Teddy because Teddy was helping Leonard to continue his search for his wife\'s killer, who actually didn\'t die when Leonard believed she did because Sammy\'s story is actually Leonard\'s story.  ',
' Misery (1990) ':' Paul burns the copy of the book Annie forced him to write, forces her to eat the ashes and then slams her head against a pig statue killing her.  ',
' Mission: Impossible (1996)  ':' Jim and Claire Phelps were behind the whole thing, they are killed, Max is apprehended, and Ethan Hunt is asked in code if he is ready for his next mission.  ',
' Monsters, Inc. (2001) ':' It turns out laughter was 10 times stronger than screaming, thus solving the power problem, and Boo and Sully are reunited. ',
' Monsters vs. Aliens (2009)  ':' Insectasorous becomes a butterfly, and the aliens are defeated. ',
' Moulin Rouge! (2001)  ':' Satine dies of consumption. ',
' Murder on the Orient Express (1974) ':' It turns out all 13 passengers took a turn at stabbing Ratchett, thereby making impossible to know who truly killed him. Since Ratchett deserved his death, Poirot agrees to let them get away with it. ',
' National Treasure (2004)  ':' They find the treasure, and aren\'t arrested. ',
' National Treasure: Book of Secrets (2007) ':' Mitch sacrifices himself so the rest of them can get out of the tomb. ',
' Next (2007) ':' The entire second half of the film is a vision Cris had while having sex with Liz.  ',
' Over the Hedge (2006) ':' Vincent is taken away by animal control, and Dwayne & Gladys are arrested for installing a Depelter Turbo in her yard. RJ is finally accepted by the animals into their family. ',
' Pan\'s Labyrinth (2006) ':' Ofelia is killed by Captain Vidal, but rules the underworld as a princess.  ',
' Pinocchio (1940)  ':' Pinocchio becomes a real boy and Jiminy Crickit becomes a conscious.  ',
' Pinocchio\'s Revenge (1996) ':' It turns out that Zoe was the killer, and she is committed to a mental hospital.  ',
' Pirates of the Caribbean: The Curse of the Black Pearl... (2003)  ':' Jack shoots Barbossa just as the curse is lifted. ',
' Pirates of the Caribbean: Dead Man\'s Chest (2006)  ':' Elizabeth tricks Jack into staying on the Pearl as the Kraken drags the ship down. The crew plans to to Davy Jones Locker to get him, and Barbossa, alive and well, offers to be their captain. ',
' Pirates of the Caribbean: At World\'s End (2007)  ':' Davy Jones stabs Will and he dies, but not before Jack allows Will to stab the heart of Davy Jones, which allows Will to resurrect and become the new Davy Jones, and Elizabeth stays on a deserted island with his heart where ten years later, Will returns to find he now has a son. Also, Lord Beckett, Mercer, Elizabeth\'s father, James Norrington, and Sao Feng die.  ',
' Pirates of the Caribbean: On Stranger Tides (2011)  ':' Barbossa stabs Blackbeard and Angelica is poisoned by a blade. They must make a decision to save one or the other with the fountain of youth. Blackbeard decides to save his own life, but Jack switched the chalices, thus allowing Angelica to survive at the cost of Blackbeard\'s life. ',
' Planet of the Apes (1968) ':' They were on earth the whole time.  ',
' The Poseidon Adventure (1972) ':' Rev. Scott loses his faith and sacrifices himself to save the rest of the passengers. James Martin, Manny Rosen, Mike Rogo, Nonnie, Robin & Susan are the only survivors. ',
' The Prestige (2006) ':' Alfred Borden was actually twins who would switch every time they did the trick. One of the twins is hanged and the other twin shoots Angier. ',
' The Prince Of Egypt (1998)  ':' Moses leads the Jews out of Egypt and heads to Mount Sinai where he receives the ten commandments.  ',
' The Princess Bride (1987) ':' Buttercup, Westley, Inigo, and Fezzick all make it out of the castle alive, and escape. The grandson asks his grandfather if he can come back tomorrow and read the book again. The grandfather replies, "As you wish." ',
' The Proposal (2009) ':' Sandra Bullock and Ryan Reynolds end up together. ',
' Psycho (1960) ':' Norman Bates dressed up as his dead mother and killed people. ',
' Puss In Boots (2011)  ':' The whole film was a revenge plot by Humpty Dumpty against Puss, but Humpty decides to sacrifice himself to save the town from the wrath of an angry goose. ',
' Ratatouille (2007)  ':' Ego writes a positive review of Gusteau\'s, but the restaurant is closed down because of a health violation. Then Linguini and Collette open a new restaurant where both humans and rats can enjoy fine cuisine.  ',
' Rear Window (1954)  ':' Thorwald killed his wife, and attempted to kill Jimmy Stewart, but is caught by the police. ',
' Rebecca (1940)  ':' Rebecca found out she had cancer and tried to entice her husband to kill her. Mrs. Danvers burns the manor and dies inside. ',
' The Road To El Dorado (2000)  ':' The treasures are lost and the door to El Dorado is sealed forever. ',
' Rocky (1976)  ':' Rocky loses the fight, but goes the distance with Creed.  ',
' Rocky II (1979) ':' Rocky wins the fight. ',
' Rocky III (1982)  ':' Rocky loses the first match, Mickey dies, and then Rocky gets a rematch and then wins the fight.  ',
' Rocky IV (1985) ':' Rocky wins the fight. ',
' Rocky V (1990)  ':' Rocky wins the street fight and then punches Duke once in the face. ',
' Rocky Balboa (2006) ':' Rocky loses the fight.  ',
' Saw (2004)  ':' John (the corpse) is Jigsaw and leaves Adam to die. ',
' Scream (1996) ':' Billy and Stu are both Ghostface. ',
' Scream 2 (1997) ':' Mickey and Mrs. Loomis (aka Debbie Salt) are both Ghostface.  ',
' Seven (1995)  ':' John Doe wanted Brad Pitt to kill him after he killed his pregnant wife and mailed her decapitated head to him. Brad Pitt does kill him, thus fulfilling John Doe\'s masterpiece. Brad Pitt is arrested for shooting an unarmed, chained suspect. ',
' Seven Pounds (2008) ':' Tim commits suicide and donates his organs to seven people. ',
' Shadow of a Doubt (1943)  ':' Uncle Charlie tries to kill Charlotte by pushing her off the train, but after they fight, she pushes him into an oncoming train. Everyone else believes it was an accident. Charlotte and Jack decide to keep his crimes and the truth of his death a secret. ',
' Shark Tale (2004) ':' Oscar finally admits the whole things was a lie and the sharks and fish live in harmony.  ',
' The Shawshank Redemption (1994) ':' Tim Robbins escapes from prison, the warden commits suicide after his crimes are discovered, and Morgan Freeman is released from prison and meets up with Tim Robbins.  ',
' Shrek (2001)  ':' Fiona turns into an ogre at night, and she and Shrek fall in love, thus she becomes an ogre permanantly.  ',
' Shrek 2 (2004)  ':' Shrek and Fiona decide to remain ogres, and the fairy godmother dies. ',
' Shrek the Third (2007)  ':' Artie becomes king of Far Far Away. ',
' Shrek Forever After (2010)  ':' Shrek and Fiona kiss just before the sunrise, thus allowing Shrek to return back to his normal timeline.  ',
' Shutter Island (2010) ':' The whole movie was a plan by the hospital to get the Teddy, who is actually Andrew Laeddis, to remember that he had killed his wife who had murdered their three children. But he regresses back and thus is taken to be lobotomized.  ',
' Sinbad: Legend of the Seven Seas (2003) ':' Proteous lets Marina join Sinbad\'s crew. ',
' The Sixth Sense (1999)  ':' Bruce Willis was dead for the whole film. ',
' Sleuth (1972) ':' The insurance fraud was actually just a cover so Andrew could kill Milo. It turns out the gun had blanks in it, and Andrew was just screwing with Milo. Inspector Doppler is actually Milo in disguise. Milo killed Thea for real, and dares Andrew to solve it before the police show up. Then it turns out the whole thing was a ruse so Andrew could be beaten by his own game twice. Andrew then shoots Milo for real out of anger, just as the police show up, showing Milo getting the last laugh, implying he planned for him to be arrested for his real murder.  ',
' Snow White and the Seven Dwarfs (1937)  ':' The queen falls off a cliff and dies. Prince Charming kisses Snow White and she comes back to life. ',
' Some Like It Hot (1959) ':' Marilyn Monroe and Tony Curtis end up together. Daphne tries to talk Osgood out of marrying her/him. When Daphne finally admits he\'s a man, Osgood responds with, "Well, nobody\'s perfect." ',
' Source Code (2011)  ':' The guy who always leaves his wallet on the train is the bomber, & Captain Colter decides to remain inside the Source Code in an alternate timeline where the train isn\'t bombed, living as Sean Fentress. ',
' Soylent Green (1973)  ':' Soylent Green is made of people.  ',
' Speed (1994)  ':' The terrorist is decapitated and Sandra Bullock and Keeanu Reeves end up together.  ',
' Speed 2: Cruise Control (1997)  ':' The ship is finally stopped, and the villain dies.  ',
' Speed Racer (2008)  ':' Speed Racer wins the race and Racer X is Rex. ',
' Spirit: Stallion Of The Cimarron (2002) ':' Spirit and Rain make it back to their families. ',
' Star Wars: Episode V - The Empire Strikes Back... (1980)  ':' Darth Vader is Luke Skywalker\'s father.  ',
' Suspicion (1941)  ':' Johnnie was actually planning to commit suicide so Lina could get some insurance money. ',
' Tangled (2010)  ':' Flynn/Eugene is stabbed by Mother Gothel and Rapunzel attempts to save him, but he cuts her hair, which causes Mother Gothel to turn to dust. Eugene dies, but Rapunzel cries and her tears bring him back to life. Rapunzel goes back to the kingdom as the princess and she and Eugene get married. ',
' There Will Be Blood (2007)  ':' Daniel Plainview disowns his son, gets Eli Sunday to denounce his faith, and then blungeons him to death with a bowling pin.  ',
' Titanic (1997)  ':' The ship sinks and Jack dies. ',
' Titanic: The Legend Goes On... (2000) ':' William and Angelica both survive and get married. Oh and the ship sinks. ',
' To Kill a Mockingbird (1962)  ':' Bob Ewell tries to attack Scout and Jem, but Boo Radley comes out of the house and saves them by killing Ewell. ',
' Toy Story (1995)  ':' Woody and Buzz make back to Andy just before they move. ',
' Toy Story 2 (1999)  ':' Woody decides to go back to Andy and brings Jessie and Bullseye with him. ',
' Toy Story 3 (2010)  ':' Andy drops off his toys at a little girl\'s house before he heads off to college. ',
' True Grit (1969)  ':' LaBeouf dies, Mattie is bitten by a snake, and Rooster saves her life. She later asks him if he would be buried in her family plot as a way to thank him. ',
' True Grit (2010)  ':' Mattie is bitten by a snake and her arm has to be amputated. Years later she tries to find Rooster to thank him to only find that he is now dead. She moves his body to Yell County and goes out to find LaBeouf. ',
' The Truman Show (1998)  ':' Truman hits the edge of the studio, finds out that his life was televised for the whole world, and after talking with Christof, decides to leave his fake televised world behind and heads off into the real world. ',
' Twins (1988)  ':' Julies and Vincent return the money, and with the reward money they pay off Vincent\'s debt and use the rest to start a consulting business. Then they are reunited with their mother.  ',
' Unknown (2011)  ':' Martin Harris was actually a trained assassin and Martin Harris was simply a cover in a group\'s plan to assassinate Professor Bressler, but the accident led him to believe that he actually was his cover. After stopping the plot from happening, Harris and Gina obtain new identies, passports and flee the country. ',
' Up (2009) ':' Charles Muntz falls to his death, and Carl is finally able to let go of Ellie and becomes a father figure for Russell.  ',
' The Usual Suspects (1995) ':' Kevin Spacey\'s character is Keyser Soze and he gets away.  ',
' Vertigo (1958) (1958) ':' Gavin hired Judy Barton to pretend to be his wife Madeline and hired Scotty to follow her so he could claim she was mentally unstable. The reason he hired Scotty was because of his newfound acrophobia, he didn\'t follow Judy when she ran up to the clock tower where Scotty threw his wife\'s corpse off the top.  ',
' Waking Ned Devine (1998)  ':' The whole entire town fools the lotto guy into believing that David Kelly is Ned Devine. Lizzie tries to call the lotto company from a phone booth in an attempt to get everyone arrested so she can get 10% of the price of the ticket, but the phone booth is hit by a car with her inside, sending her falling down a cliff to her death.  ',
' Wallace & Gromit: The Curse of the Were-Rabbit... (2005)  ':' Wallace is brought back to his human form and Lady Tottingham opens a sanctuary for rabbits.  ',
' WALL·E (2008) ':' AUTO is defeated and the ship makes it back to earth. ',
' The War of the Worlds (1953)  ':' The aliens all die after being exposed to earth germs.  ',
' Witness for the Prosecution (1957)  ':' Leonard did kill Emily French, and Christine became a witness for the prosecution and allowed herself to be discredited, because it would be a stronger case than the testimony of a spouse.  ',
' The Wizard of Oz (1939) ':' It was all a dream. ',
' You\'ve Got Mail (1998) ':' Meg Ryan and Tom Hanks end up together. '
}

async def spoilme(client, message):
	try:
		if message.channel.is_private == False and 'spoil' in message.channel.name:
			movie = str(random.choice(list(SPOILERS.keys())))
			spoil = str(SPOILERS[movie])      
			await client.send_message(message.channel, "Are you ready? I'm finding a movie to spoil for you")
			time.sleep(2)
			await client.send_message(message.channel, "Have you seen the movie \"{}\"".format(movie))
			time.sleep(3)
			await client.send_message(message.channel, "Did you know that: {}".format(spoil))
		else:
			await client.send_message(message.channel, "I'm only allowed to spoil in the spoil channel.")
	except:
		print(1)
		await client.send_message(message.channel, "I don't understand what happened. Everything works perfect on my machine. You must have done something wrong.")